definitions:
  controller.createRecipeRequest:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  controller.recipeDTO:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
  description: Simple recipes service with CRUD endpoints.
  title: Recipes API
  version: "1.0"
paths:
  /recipes:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controller.recipeDTO'
            type: array
      summary: List recipes
      tags:
      - recipes
    post:
      parameters:
      - description: Create recipe payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/controller.createRecipeRequest'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controller.recipeDTO'
      summary: Create a new recipe
      tags:
      - recipes
swagger: "2.0"
